services:
  # web:
  #   image: levantamentos
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - db
  #   env_file:
  #     - .env.production

  db:
    # image working with m1 chips mysql
    image: mysql/mysql-server:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: levantamentos
      MYSQL_USER: user1

