services:
  # web:
  #   image: levantamentos
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - db
  #   env_file:
  #     - .env.production

  db:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Qys2JEdRs-99gVtJ
      POSTGRES_DB: levantamentos
