-- MySQL Script generated by MySQL Workbench
-- Sat May 25 19:54:49 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema levantamentos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema levantamentos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `levantamentos` DEFAULT CHARACTER SET utf8 ;
USE `levantamentos` ;

-- -----------------------------------------------------
-- Table `levantamentos`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `levantamentos`.`user` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `emailVerified` TIMESTAMP NULL,
  `image` TEXT NULL,
  `password` VARCHAR(200) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `levantamentos`.`session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `levantamentos`.`session` (
  `id` INT NOT NULL,
  `sessionToken` VARCHAR(45) NULL,
  `user_id` INT NOT NULL,
  `expires` TIMESTAMP NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_Session_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_Session_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `levantamentos`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `levantamentos`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `levantamentos`.`account` (
  `id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `type` VARCHAR(255) NULL,
  `refresh_token` VARCHAR(255) NULL,
  `acess_token` VARCHAR(255) NULL,
  `expires_at` FLOAT NULL,
  `token_type` VARCHAR(255) NULL,
  `scope` VARCHAR(255) NULL,
  `id_token` VARCHAR(255) NULL,
  `session_state` VARCHAR(255) NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_Account_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_Account_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `levantamentos`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `levantamentos`.`proposta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `levantamentos`.`proposta` (
  `id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `dataCriacao` TIMESTAMP NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_proposta_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_proposta_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `levantamentos`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `levantamentos`.`foto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `levantamentos`.`foto` (
  `id` INT NOT NULL,
  `caminhoRelativo` TEXT NULL,
  `dataCriacao` TIMESTAMP NULL,
  `tipo` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `levantamentos`.`tipo_iluminacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `levantamentos`.`tipo_iluminacao` (
  `id` INT NOT NULL,
  `tipo` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `levantamentos`.`luminaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `levantamentos`.`luminaria` (
  `id` INT NOT NULL,
  `ref_luminaria` VARCHAR(45) NOT NULL,
  `tipo_iluminacao_id` INT NOT NULL,
  `potencia_lampada` FLOAT NULL,
  `quant_lampadas` INT NULL,
  `foto_id` INT NOT NULL,
  PRIMARY KEY (`id`, `tipo_iluminacao_id`, `foto_id`),
  UNIQUE INDEX `ref_luminaria_UNIQUE` (`ref_luminaria` ASC) VISIBLE,
  INDEX `fk_luminaria_foto1_idx` (`foto_id` ASC) VISIBLE,
  INDEX `fk_luminaria_tipo_iluminacao1_idx` (`tipo_iluminacao_id` ASC) VISIBLE,
  CONSTRAINT `fk_luminaria_foto1`
    FOREIGN KEY (`foto_id`)
    REFERENCES `levantamentos`.`foto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_luminaria_tipo_iluminacao1`
    FOREIGN KEY (`tipo_iluminacao_id`)
    REFERENCES `levantamentos`.`tipo_iluminacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `levantamentos`.`iluminacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `levantamentos`.`iluminacao` (
  `id` INT NOT NULL,
  `quantidade` FLOAT NOT NULL,
  `dataCriacao` TIMESTAMP NULL,
  `luminaria_id` INT NOT NULL,
  `foto_id` INT NOT NULL,
  PRIMARY KEY (`id`, `luminaria_id`, `foto_id`),
  INDEX `fk_iluminacao_luminaria1_idx` (`luminaria_id` ASC) VISIBLE,
  INDEX `fk_iluminacao_foto1_idx` (`foto_id` ASC) VISIBLE,
  CONSTRAINT `fk_iluminacao_luminaria1`
    FOREIGN KEY (`luminaria_id`)
    REFERENCES `levantamentos`.`luminaria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_iluminacao_foto1`
    FOREIGN KEY (`foto_id`)
    REFERENCES `levantamentos`.`foto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `levantamentos`.`edificio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `levantamentos`.`edificio` (
  `id` INT NOT NULL,
  `designacao` VARCHAR(255) NULL,
  `descricao` VARCHAR(255) NULL,
  `proposta_id` INT NOT NULL,
  `foto_edificio` TEXT NULL,
  `iluminacao_id` INT NOT NULL,
  `foto_id` INT NOT NULL,
  PRIMARY KEY (`id`, `proposta_id`, `iluminacao_id`, `foto_id`),
  INDEX `fk_edificios_propostas1_idx` (`proposta_id` ASC) VISIBLE,
  INDEX `fk_edificio_iluminacao1_idx` (`iluminacao_id` ASC) VISIBLE,
  INDEX `fk_edificio_foto1_idx` (`foto_id` ASC) VISIBLE,
  CONSTRAINT `fk_edificios_propostas1`
    FOREIGN KEY (`proposta_id`)
    REFERENCES `levantamentos`.`proposta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_edificio_iluminacao1`
    FOREIGN KEY (`iluminacao_id`)
    REFERENCES `levantamentos`.`iluminacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_edificio_foto1`
    FOREIGN KEY (`foto_id`)
    REFERENCES `levantamentos`.`foto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `levantamentos`.`piso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `levantamentos`.`piso` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `edificio_id` INT NOT NULL,
  PRIMARY KEY (`id`, `edificio_id`),
  INDEX `fk_pisos_edificios1_idx` (`edificio_id` ASC) VISIBLE,
  CONSTRAINT `fk_pisos_edificios1`
    FOREIGN KEY (`edificio_id`)
    REFERENCES `levantamentos`.`edificio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `levantamentos`.`ocupacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `levantamentos`.`ocupacao` (
  `id` INT NOT NULL,
  `atividade` VARCHAR(255) NULL,
  `perfil_ocup` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `levantamentos`.`tipo_protecoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `levantamentos`.`tipo_protecoes` (
  `id` INT NOT NULL,
  `protecao_interior` VARCHAR(255) NULL,
  `protecao_exterior` VARCHAR(255) NULL,
  `protecao_intermedia` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `levantamentos`.`tipo_envidracados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `levantamentos`.`tipo_envidracados` (
  `id` INT NOT NULL,
  `ref_vao` VARCHAR(45) NOT NULL,
  `tipo_vao` VARCHAR(255) NOT NULL,
  `tipo_caixilharia` VARCHAR(255) NOT NULL,
  `tipo_vidro` VARCHAR(255) NOT NULL,
  `med_vidro` VARCHAR(255) NULL,
  `tipo_envidracadoscol` VARCHAR(45) NULL,
  `foto_med` TEXT NULL,
  `protecoes_id` INT NOT NULL,
  `foto_id` INT NOT NULL,
  PRIMARY KEY (`id`, `protecoes_id`, `foto_id`),
  UNIQUE INDEX `ref_vao_UNIQUE` (`ref_vao` ASC) VISIBLE,
  INDEX `fk_tipo_envidracados_protecoes1_idx` (`protecoes_id` ASC) VISIBLE,
  INDEX `fk_tipo_envidracados_foto1_idx` (`foto_id` ASC) VISIBLE,
  CONSTRAINT `fk_tipo_envidracados_protecoes1`
    FOREIGN KEY (`protecoes_id`)
    REFERENCES `levantamentos`.`tipo_protecoes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tipo_envidracados_foto1`
    FOREIGN KEY (`foto_id`)
    REFERENCES `levantamentos`.`foto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `levantamentos`.`envidracados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `levantamentos`.`envidracados` (
  `id` INT NOT NULL,
  `quant_vao` INT NOT NULL,
  `dataCriacao` TIMESTAMP NULL,
  `tipo_envidracados_id` INT NOT NULL,
  PRIMARY KEY (`id`, `tipo_envidracados_id`),
  INDEX `fk_envidracados_tipo_envidracados1_idx` (`tipo_envidracados_id` ASC) VISIBLE,
  CONSTRAINT `fk_envidracados_tipo_envidracados1`
    FOREIGN KEY (`tipo_envidracados_id`)
    REFERENCES `levantamentos`.`tipo_envidracados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `levantamentos`.`tipo_sistemas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `levantamentos`.`tipo_sistemas` (
  `id` INT NOT NULL,
  `ref_sistema` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(255) NULL,
  `tipo` VARCHAR(255) NULL,
  `fonte_energia` VARCHAR(255) NULL,
  `marca` VARCHAR(255) NULL,
  `modelo` VARCHAR(255) NULL,
  `funcao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ref_sistema_UNIQUE` (`ref_sistema` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `levantamentos`.`sistemas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `levantamentos`.`sistemas` (
  `id` INT NOT NULL,
  `quant_sistemas` INT NOT NULL,
  `tipo_sistemas_id` INT NOT NULL,
  `dataCriacao` TIMESTAMP NULL,
  PRIMARY KEY (`id`, `tipo_sistemas_id`),
  INDEX `fk_sistemas_tipo_sistemas1_idx` (`tipo_sistemas_id` ASC) VISIBLE,
  CONSTRAINT `fk_sistemas_tipo_sistemas1`
    FOREIGN KEY (`tipo_sistemas_id`)
    REFERENCES `levantamentos`.`tipo_sistemas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `levantamentos`.`espaco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `levantamentos`.`espaco` (
  `id` INT NOT NULL,
  `edificio_id` INT NOT NULL,
  `piso_id` INT NOT NULL,
  `numero` INT NOT NULL AUTO_INCREMENT,
  `designacao` VARCHAR(255) NULL,
  `peDireito` FLOAT NOT NULL,
  `climatizado` TINYINT NOT NULL,
  `util` TINYINT NOT NULL,
  `numero_ocupantes` INT NULL,
  `ocupacao_id` INT NOT NULL,
  `iluminacao_id` INT NOT NULL,
  `envidracados_id` INT NOT NULL,
  `sistemas_id` INT NOT NULL,
  `foto_id` INT NOT NULL,
  PRIMARY KEY (`id`, `edificio_id`, `piso_id`, `ocupacao_id`, `iluminacao_id`, `envidracados_id`, `sistemas_id`, `foto_id`),
  INDEX `fk_espacos_pisos1_idx` (`piso_id` ASC) VISIBLE,
  INDEX `fk_espacos_edificios1_idx` (`edificio_id` ASC) VISIBLE,
  UNIQUE INDEX `numero_UNIQUE` (`numero` ASC) VISIBLE,
  INDEX `fk_espacos_ocupacao1_idx` (`ocupacao_id` ASC) VISIBLE,
  INDEX `fk_espaco_iluminacao1_idx` (`iluminacao_id` ASC) VISIBLE,
  INDEX `fk_espaco_envidracados1_idx` (`envidracados_id` ASC) VISIBLE,
  INDEX `fk_espaco_foto1_idx` (`foto_id` ASC) VISIBLE,
  INDEX `fk_espaco_sistemas1_idx` (`sistemas_id` ASC) VISIBLE,
  CONSTRAINT `fk_espacos_pisos1`
    FOREIGN KEY (`piso_id`)
    REFERENCES `levantamentos`.`piso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_espacos_edificios1`
    FOREIGN KEY (`edificio_id`)
    REFERENCES `levantamentos`.`edificio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_espacos_ocupacao1`
    FOREIGN KEY (`ocupacao_id`)
    REFERENCES `levantamentos`.`ocupacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_espaco_iluminacao1`
    FOREIGN KEY (`iluminacao_id`)
    REFERENCES `levantamentos`.`iluminacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_espaco_envidracados1`
    FOREIGN KEY (`envidracados_id`)
    REFERENCES `levantamentos`.`envidracados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_espaco_foto1`
    FOREIGN KEY (`foto_id`)
    REFERENCES `levantamentos`.`foto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_espaco_sistemas1`
    FOREIGN KEY (`sistemas_id`)
    REFERENCES `levantamentos`.`sistemas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `levantamentos`.`elevadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `levantamentos`.`elevadores` (
  `id` INT NOT NULL,
  `ref_elevador` VARCHAR(45) NOT NULL,
  `carga` INT NOT NULL,
  `piso_id` INT NOT NULL,
  `piso_edificio_id` INT NOT NULL,
  `dataCriacao` TIMESTAMP NULL,
  `foto_id` INT NOT NULL,
  PRIMARY KEY (`id`, `piso_id`, `piso_edificio_id`, `foto_id`),
  UNIQUE INDEX `ref_elevador_UNIQUE` (`ref_elevador` ASC) VISIBLE,
  INDEX `fk_elevadores_piso1_idx` (`piso_id` ASC, `piso_edificio_id` ASC) VISIBLE,
  INDEX `fk_elevadores_foto1_idx` (`foto_id` ASC) VISIBLE,
  CONSTRAINT `fk_elevadores_piso1`
    FOREIGN KEY (`piso_id` , `piso_edificio_id`)
    REFERENCES `levantamentos`.`piso` (`id` , `edificio_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_elevadores_foto1`
    FOREIGN KEY (`foto_id`)
    REFERENCES `levantamentos`.`foto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
